<template>
  <div class="space-y-6">
    <div v-if="showHeader">
      <h2 class="text-3xl font-bold text-white">{{ resolvedHeading }}</h2>
      <p v-if="resolvedSubheading" class="mt-2 text-gray-400">{{ resolvedSubheading }}</p>
    </div>

    <div v-if="isLoading" class="rounded-lg bg-zinc-900 px-6 py-12 text-center text-white">
      <div class="inline-block">
        <div class="mb-4 h-12 w-12 animate-spin rounded-full border-b-2 border-blue-500"></div>
        <p>{{ t('edit.loading') }}</p>
      </div>
    </div>

    <div v-else :class="['video-editor-layout', { 'video-editor-layout-stacked': stackedLayout }]">
      <form class="space-y-6 rounded-lg border border-zinc-700 bg-zinc-900 p-8" @submit.prevent="handleSave">
        <section class="space-y-6 rounded-2xl border border-zinc-800 bg-zinc-950/65 p-5">
          <div>
            <label class="mb-2 block text-sm font-medium text-white">{{ t('edit.videoTitle') }}</label>
            <input v-model="form.title" type="text" required :placeholder="t('upload.videoTitlePlaceholder')" class="w-full rounded border border-zinc-700 bg-zinc-800 px-4 py-2 text-white placeholder-gray-500 focus:border-blue-500 focus:outline-none transition" />
          </div>

          <div>
            <label class="mb-2 block text-sm font-medium text-white">{{ t('edit.description') }}</label>
            <textarea v-model="form.description" rows="8" :placeholder="t('edit.descriptionHelper')" class="w-full resize-none rounded border border-zinc-700 bg-zinc-800 px-4 py-2 text-white placeholder-gray-500 focus:border-blue-500 focus:outline-none transition" />
          </div>

          <div class="grid gap-4 xl:grid-cols-2">
            <div class="flex items-center gap-3 rounded border border-zinc-700 bg-zinc-800 p-4">
              <input id="explicit-toggle" v-model="form.explicit" type="checkbox" class="h-4 w-4 cursor-pointer rounded accent-red-500" />
              <label for="explicit-toggle" class="flex-1 cursor-pointer">
                <span class="text-sm font-medium text-white">{{ t('edit.explicit') }}</span>
                <p class="mt-1 text-xs text-gray-400">{{ t('edit.explicitHelper') }}</p>
              </label>
            </div>

            <div>
              <label class="mb-2 block text-sm font-medium text-white">{{ t('edit.category') }}</label>
              <select v-model="form.categoryId" class="w-full rounded border border-zinc-700 bg-zinc-800 px-4 py-2 text-white focus:border-blue-500 focus:outline-none">
                <option value="">{{ t('edit.noCategory') }}</option>
                <option v-for="category in categories" :key="category.id" :value="category.id">
                  {{ category.name }}
                </option>
              </select>
            </div>
          </div>
        </section>

        <section class="space-y-5 rounded-2xl border border-zinc-800 bg-zinc-950/65 p-5">
          <div>
            <h3 class="text-lg font-semibold text-white">{{ t('edit.thumbnail') }}</h3>
            <p class="mt-1 text-sm text-gray-400">{{ t('edit.currentThumbnail') }}</p>
          </div>

          <div class="relative aspect-video max-w-lg overflow-hidden rounded border border-zinc-700 bg-zinc-800">
            <img v-if="currentThumbnailUrl" :src="currentThumbnailUrl" :alt="form.title" class="h-full w-full object-cover" @error="handleImageError" />
            <div v-else class="flex h-full w-full items-center justify-center text-gray-600">
              <svg class="h-12 w-12" fill="currentColor" viewBox="0 0 20 20"><path d="M2 6a2 2 0 012-2h12a2 2 0 012 2v8a2 2 0 01-2 2H4a2 2 0 01-2-2V6zM14.553 7.106A1 1 0 0014 7H6a1 1 0 00-.553.106A1 1 0 004 8v4a1 1 0 001.447.894l4-2.667a1 1 0 000-1.788l-4-2.667z" /></svg>
            </div>
          </div>
          <p class="text-xs" :class="hasCustomThumbnail ? 'text-blue-400' : 'text-gray-400'">
            {{ hasCustomThumbnail ? t('edit.customThumbnail') : t('edit.autoGenerated') }}
          </p>

          <div class="rounded-xl border border-dashed border-zinc-700 bg-zinc-900/70 p-5 text-center transition hover:border-blue-500 cursor-pointer" @click="triggerFileInput">
            <svg class="mx-auto mb-2 h-12 w-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
            </svg>
            <p class="text-sm text-gray-300">{{ t('edit.thumbnailClick') }}</p>
            <p class="mt-1 text-xs text-gray-500">{{ t('edit.thumbnailFormat') }}</p>
            <input ref="fileInput" type="file" accept="image/*" class="hidden" @change="onThumbnailSelected" />
          </div>
          <p class="text-xs text-gray-400">{{ t('edit.maxSize') }}</p>

          <div v-if="thumbnailPreview" class="space-y-2">
            <label class="block text-sm font-medium text-white">{{ t('edit.newThumbnailPreview') }}</label>
            <div class="relative aspect-video max-w-lg overflow-hidden rounded border-2 border-blue-500 bg-zinc-800">
              <img :src="thumbnailPreview" :alt="form.title" class="h-full w-full object-cover" />
            </div>
            <button type="button" class="text-sm text-red-400 transition hover:text-red-300" @click="clearThumbnail">
              {{ t('edit.removeNew') }}
            </button>
          </div>

          <div v-if="hasCustomThumbnail && !thumbnailPreview">
            <button type="button" class="rounded bg-yellow-600 px-4 py-2 text-sm font-medium transition hover:bg-yellow-700" @click="revertToAutoThumbnail">
              {{ t('edit.revertAuto') }}
            </button>
          </div>
        </section>

        <div v-if="error" class="rounded border border-red-700 bg-red-900 p-4 text-red-200">
          {{ error }}
        </div>
        <div v-if="successMessage" class="rounded border border-green-700 bg-green-900 p-4 text-green-200">
          {{ successMessage }}
        </div>

        <div class="flex gap-4 border-t border-zinc-700 pt-6">
          <button type="submit" :disabled="isSaving" class="flex-1 rounded bg-blue-600 px-6 py-2 font-medium text-white transition hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50">
            {{ isSaving ? t('edit.saving') : t('edit.saveChanges') }}
          </button>
          <NuxtLink v-if="showCancel && cancelTo" :to="cancelTo" class="flex-1 rounded bg-zinc-700 px-6 py-2 text-center font-medium text-white transition hover:bg-zinc-600">
            {{ t('common.cancel') }}
          </NuxtLink>
        </div>
      </form>

      <div class="space-y-6">
        <VideoTrackManager :video-id="videoId" :video-title="form.title" stacked />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, onMounted, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { getVideo, updateVideo } from '~/app/service/videos'
import { resolveMediaUrl } from '~/app/utils/media'
import VideoTrackManager from '~/app/components/admin/VideoTrackManager.vue'

const props = withDefaults(defineProps<{
  videoId: string
  heading?: string
  subheading?: string
  showHeader?: boolean
  showCancel?: boolean
  cancelTo?: string
  redirectAfterSave?: string
  stackedLayout?: boolean
}>(), {
  heading: '',
  subheading: '',
  showHeader: true,
  showCancel: false,
  cancelTo: '',
  redirectAfterSave: '',
  stackedLayout: false,
})

const router = useRouter()
const { t } = useI18n()
const resolvedHeading = computed(() => props.heading || t('videoEditor.title'))
const resolvedSubheading = computed(() => props.subheading !== undefined ? props.subheading : t('admin.videos.editorBody'))
const isLoading = ref(true)
const isSaving = ref(false)
const error = ref('')
const successMessage = ref('')
const fileInput = ref<HTMLInputElement>()

const form = ref({
  title: '',
  description: '',
  explicit: false,
  categoryId: '',
})

const thumbnailPreview = ref('')
const currentThumbnailUrl = ref('')
const hasCustomThumbnail = ref(false)
const thumbnailFile = ref<File | null>(null)
const categories = ref<any[]>([])
const uploadApiBaseURL = import.meta.env.VITE_API_BASE_URL || '/api/v1'

const loadCategories = async () => {
  try {
    const response = await fetch('/api/v1/categories/all')
    if (response.ok) {
      categories.value = await response.json()
    }
  } catch (err) {
    console.error('Failed to load categories:', err)
  }
}

const loadVideo = async () => {
  if (!props.videoId) return
  try {
    isLoading.value = true
    error.value = ''
    const video = await getVideo(props.videoId)
    form.value.title = video.title || ''
    form.value.description = video.description || ''
    form.value.explicit = video.explicit === true || video.explicit === 'true' || false
    form.value.categoryId = video.categories?.[0]?.id || ''

    currentThumbnailUrl.value = video.thumbnail_url
      ? (video.thumbnail_url.startsWith('http') ? video.thumbnail_url : resolveMediaUrl(video.thumbnail_url))
      : ''
    hasCustomThumbnail.value = video.has_custom_thumbnail || false
    thumbnailPreview.value = ''
    thumbnailFile.value = null
  } catch (err) {
    error.value = t('edit.loadError')
    console.error('Load video error:', err)
  } finally {
    isLoading.value = false
  }
}

onMounted(async () => {
  await loadCategories()
  await loadVideo()
})

watch(() => props.videoId, async (next, prev) => {
  if (next && next !== prev) {
    await loadVideo()
  }
})

const triggerFileInput = () => {
  fileInput.value?.click()
}

const onThumbnailSelected = (event: Event) => {
  const input = event.target as HTMLInputElement
  const file = input.files?.[0]
  if (!file) return
  if (file.size > 5 * 1024 * 1024) {
    error.value = t('upload.thumbnailSizeError')
    return
  }
  if (!file.type.startsWith('image/')) {
    error.value = t('upload.thumbnailTypeError')
    return
  }
  error.value = ''
  thumbnailFile.value = file
  const reader = new FileReader()
  reader.onload = (e) => {
    thumbnailPreview.value = e.target?.result as string
  }
  reader.readAsDataURL(file)
}

const clearThumbnail = () => {
  thumbnailFile.value = null
  thumbnailPreview.value = ''
  if (fileInput.value) {
    fileInput.value.value = ''
  }
}

const revertToAutoThumbnail = () => {
  thumbnailFile.value = null
  thumbnailPreview.value = ''
  hasCustomThumbnail.value = false
  currentThumbnailUrl.value = ''
}

const handleImageError = () => {
  currentThumbnailUrl.value = ''
}

const handleSave = async () => {
  error.value = ''
  successMessage.value = ''
  if (!form.value.title.trim()) {
    error.value = t('upload.titleRequiredError')
    return
  }

  isSaving.value = true
  try {
    const updateData: any = {
      title: form.value.title,
      description: form.value.description,
      explicit: form.value.explicit,
    }
    if (form.value.categoryId) {
      updateData.category_ids = form.value.categoryId
    }
    if (!hasCustomThumbnail.value && !thumbnailFile.value) {
      updateData.revert_to_auto_thumbnail = true
    }

    if (thumbnailFile.value) {
      const formData = new FormData()
      formData.append('title', form.value.title)
      formData.append('description', form.value.description)
      formData.append('explicit', String(form.value.explicit))
      if (form.value.categoryId) formData.append('category_ids', form.value.categoryId)
      formData.append('thumbnail', thumbnailFile.value)

      const response = await fetch(`${uploadApiBaseURL}/videos/${props.videoId}`, {
        method: 'PUT',
        headers: {
          'X-User-ID': localStorage.getItem('user_id') || '',
        },
        body: formData,
      })
      if (!response.ok) {
        throw new Error('Failed to update video')
      }
    } else {
      await updateVideo(props.videoId, updateData)
    }

    successMessage.value = t('edit.saveSuccess')
    await loadVideo()

    if (props.redirectAfterSave) {
      setTimeout(() => {
        router.push(props.redirectAfterSave)
      }, 1200)
    }
  } catch (err) {
    error.value = typeof err === 'string' ? err : t('edit.saveError')
    console.error('Save error:', err)
  } finally {
    isSaving.value = false
  }
}
</script>

<style scoped>
.video-editor-layout {
  display: grid;
  gap: 1.5rem;
}

.video-editor-layout-stacked {
  grid-template-columns: minmax(0, 1fr);
}

@media (min-width: 1024px) {
  .video-editor-layout {
    grid-template-columns: minmax(0, 1fr) minmax(0, 1fr);
    align-items: start;
  }

  .video-editor-layout-stacked {
    grid-template-columns: minmax(0, 1fr);
  }
}
</style>
